#!/usr/bin/env bash
# scripts/init-host.sh — new-machine base init + GPU driver config (M3 / §A.3)
# Idempotent. Run on a fresh Ubuntu 24.04 host BEFORE scripts/bootstrap.sh.
# Handles: user+groups, OEM kernel (Strix Halo), Vulkan driver stack, system base,
# Docker, and the Strix Halo BIOS VRAM/GTT hint. Writes hosts/<host>.env with the
# detected GPU + chosen inference path for rebuild.sh / llama-swap to consume.
set -euo pipefail

HOST_NAME="${1:-$(hostname)}"
ENV_OUT="$(dirname "$0")/../hosts/${HOST_NAME}.env"
GPU="none"; INFERENCE="cpu"

echo ">>> [init-host] base machine init for host: ${HOST_NAME}"

# --- 0.1 detect GPU ----------------------------------------------------------
GPU_PCI="$(lspci -nn 2>/dev/null | grep -iE 'vga|3d|display' || true)"
if echo "$GPU_PCI" | grep -qi '1002:1586'; then
  GPU="gfx1151"; INFERENCE="vulkan"          # AMD Strix Halo (as Z13)
elif echo "$GPU_PCI" | grep -qiE '1002:15|1002:74|1002:16'; then
  GPU="amd-other"; INFERENCE="vulkan"        # other recent AMD (RADV)
elif echo "$GPU_PCI" | grep -qi '10de:'; then
  GPU="nvidia"; INFERENCE="cpu"              # CUDA path not implemented this round
fi
echo ">>> [init-host] detected GPU=${GPU} -> INFERENCE=${INFERENCE}"

# --- 0.2 user + groups (match source host so venv/shim absolute paths work) ----
if ! id norbert >/dev/null 2>&1; then
  sudo useradd -m -u 1000 -s /bin/bash norbert
fi
sudo usermod -aG render,video,docker,sudo norbert

# --- 0.3 OEM kernel (Strix Halo only — gfx1151 needs it) -----------------------
if [ "$GPU" = "gfx1151" ]; then
  if ! uname -r | grep -qi oem; then
    echo ">>> [init-host] gfx1151 -> installing linux-oem-24.04c (reboot needed to take effect)"
    sudo apt-get -o Acquire::http::Proxy=false -o Acquire::https::Proxy=false install -y linux-oem-24.04c || true
  fi
fi

# --- 0.4 Vulkan driver stack (gfx1151 / other AMD) ------------------------------
if [ "$INFERENCE" = "vulkan" ]; then
  sudo apt-get -o Acquire::http::Proxy=false -o Acquire::https::Proxy=false install -y \
    mesa-vulkan-drivers libvulkan1 libvulkan-dev vulkan-tools \
    glslc glslang-tools spirv-headers spirv-tools
fi

# --- 0.5 system base ------------------------------------------------------------
sudo apt-get -o Acquire::http::Proxy=false -o Acquire::https::Proxy=false install -y \
  curl git rsync jq sqlite3 age smartmontools ca-certificates

# --- 0.6 Docker (CE; reuse keyring if present) ----------------------------------
if ! command -v docker >/dev/null 2>&1; then
  echo ">>> [init-host] Docker not found — run scripts/bootstrap.sh [6/6] for Docker CE install"
fi

# --- 0.7 Strix Halo BIOS VRAM/GTT hint (firmware; script cannot set it) ---------
if [ "$GPU" = "gfx1151" ]; then
  VRAM_B=$(cat /sys/class/drm/card*/device/mem_info_vram_total 2>/dev/null | head -1 || echo 0)
  VRAM_GB=$((VRAM_B/1024/1024/1024))
  if [ "${VRAM_GB:-0}" -lt 90 ]; then
    echo ">>> [init-host] ⚠️  gfx1151 but GPU-visible VRAM=${VRAM_GB}GB (expected ~96GB)"
    echo ">>> [init-host]     Owner: enter BIOS, set VRAM reservation + raise GTT/TTM (M1/§D.5: 96GB GPU / 32GB sys)."
    echo ">>> [init-host]     Until then only small models or --cpu-inference."
    [ "${ALLOW_SMALL_GPU:-0}" != "1" ] || INFERENCE="cpu"
  fi
fi

# --- 0.8 write hosts/<host>.env --------------------------------------------------
mkdir -p "$(dirname "$ENV_OUT")"
cat > "$ENV_OUT" <<EOF
# hosts/${HOST_NAME}.env — host-specific tuning (§A.3). Generated by init-host.sh $(date -u +%F).
HOST_MODEL="${HOST_NAME}"
GPU="${GPU}"
INFERENCE="${INFERENCE}"     # vulkan | cpu  (drives llama-swap backend flags)
EOF
[ "$INFERENCE" = "vulkan" ] && cat >> "$ENV_OUT" <<'EOF'
LLAMA_FLAGS_COMMON="--jinja -ub 512 -ctk q8_0 -ctv q8_0 -fa auto"
LLAMA_FLAGS_VULKAN="-ngl 999 -t 8"
EOF
[ "$INFERENCE" = "cpu" ] && cat >> "$ENV_OUT" <<'EOF'
LLAMA_FLAGS_COMMON="--jinja -ub 512 -ctk q8_0 -ctv q8_0"
LLAMA_FLAGS_CPU="-t 8"          # no -ngl: CPU inference
EOF
echo ">>> [init-host] wrote ${ENV_OUT} (GPU=${GPU} INFERENCE=${INFERENCE})"
echo ">>> [init-host] done. Next: scripts/bootstrap.sh"
